name: Data Pipeline
on:
  push:
    branches:
      - main
jobs:
  first-job:
    name : run test cases
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8 
    - name: Install dependencies
      run: |
        pip install pytest pytest-cov pytest-xdist
      working-directory: ${{ github.workspace }}
    - name: Run Pytest and generate reports
      run: pytest --cov --cov-report term-missing --junitxml=pytest-results.xml
      working-directory: ${{ github.workspace }}