name: Data Pipeline
on: workflow_dispatch
jobs:
  first-job:
    name : run test cases
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 
    - name: Install dependencies
      run: |
        pip install pytest pytest-cov
      working-directory: ${{ github.workspace }}
    - name: Run Pytest and generate reports
      run: pytest --cov
      working-directory: ${{ github.workspace }}